version: "2"
run:
  build-tags:
    - integration
    - system
  modules-download-mode: readonly
linters:
  enable:
    - revive
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: exported (type|method|function|const|var) (.+) should have comment(.+)or be unexported
      - path: (.+)\.go$
        text: Error return value of .(.*Close|.*Shutdown). is not checked
      - path: (.+)\.go$
        text: 'package-comments: should have a package comment'
      - path: (.+)\.go$
        text: 'var-naming: (.+)'
      - path: (.+)\.go$
        text: 'empty-block: this block is empty, you can remove it'
      - path: (.+)\.go$
        text: 'QF1003: could use tagged switch'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
