name: Create packages

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Package version"
        type: string
        required: true

permissions:
  contents: write
  packages: write

jobs:
  # # # # # # # # # # # # # # # # #
  # Build & Publish Containers
  # # # # # # # # # # # # # # # # #
  docker-containers:
    name: Build & Publish Containers
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

     # - name: Configure Docker Tags
     #   # https://github.com/docker/metadata-action
     #   id: meta
     #   uses: docker/metadata-action@v5
     #   with:
     #     images: ghcr.io/${{github.actor}}/piko

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: version=${{inputs.version}}
          file: build/Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ghcr.io/andydunstall/piko:${{inputs.version}}  # TODO add 'latest'
